services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: hospitality-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: Hospitality_Ecosystem
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Hospitality_Ecosystemroot1772002

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: